version: '2'
services:
    olap:
        image: mdbax4:latest
        privileged: true
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbcs
        container_name: mdbcs
        networks:
            static-network:
                ipv4_address: 172.20.0.2
        ports:
            - "4001:3306"
            - "2201:22"

    oltp:
        image: mdbsrv:latest
        privileged: true
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv
        container_name: mdbsrv
        networks:
            static-network:
                ipv4_address: 172.20.0.3
        ports:
            - "4002:3306"
            - "2202:22"


#   conda:
#        image: mdbsrv:latest
#        privileged: true
#        depends_on:
#            - spider
#        environment:
#            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
#        volumes:
#            - /Users/Shared:/mdb
#        hostname: mdbsrv3
#        container_name: mdbsrv3
#        networks:
#            static-network:
#                ipv4_address: 172.20.0.4
#        ports:
#            - "4003:3306"

    python:
        image: py:latest
        privileged: true
        ports:
            - '80:80'
        networks:
            static-network:
                ipv4_address: 172.20.0.5
        volumes:
            - /Users/Shared:/mdb
        hostname: pysrv
        container_name: pysrv

networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  ip_range: 172.28.5.0/24
