version: '2'
services:
    spider:
        image: mdbsrv:latest
        privileged: true
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv1
        container_name: mdbsrv1
        networks:
            static-network:
                ipv4_address: 172.20.0.2
        ports:
            - "4001:3306"

    node1:
        image: mdbsrv:latest
        privileged: true
        depends_on:
            - spider
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv2
        container_name: mdbsrv2
        networks:
            static-network:
                ipv4_address: 172.20.0.3
        ports:
            - "4002:3306"

    node2:
        image: mdbsrv:latest
        privileged: true
        depends_on:
            - spider
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'Y'
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv3
        container_name: mdbsrv3
        networks:
            static-network:
                ipv4_address: 172.20.0.4
        ports:
            - "4003:3306"

    node3:
        image: mdbsrv:latest
        privileged: true
        depends_on:
            - spider
        volumes:
            - /Users/Shared:/mdb
        hostname: mdbsrv4
        container_name: mdbsrv4
        networks:
            static-network:
                ipv4_address: 172.20.0.5
        ports:
            - "4004:3306"  # readwrite port
networks:
    static-network:
        ipam:
            config:
                - subnet: 172.20.0.0/16
                  ip_range: 172.28.5.0/24
